image: debian:10-slim

build_gcc:
  stage: build
  services:
  - mariadb:10.4
  variables:
    MYSQL_DATABASE: "weather_information_collector"
    MYSQL_USER: "ci_user"
    MYSQL_PASSWORD: "ci_password"
    MYSQL_ROOT_PASSWORD: "ci_root_password"
  before_script:
    - apt-get update && apt-get -y install catch cmake g++ libcurl4-gnutls-dev libmariadb-dev pkg-config
    - export CC=gcc && export CXX=g++
  script:
    - ./ci/cpplint.sh
    - mkdir ./build
    - cd ./build
    - cmake ../ -DJSON_BENCHMARK=ON
    - make -j4
    - ctest -V

# There is no official clang image at Docker Hub.
build_clang:
  stage: build
  services:
  - mariadb:10.4
  variables:
    MYSQL_DATABASE: "weather_information_collector"
    MYSQL_USER: "ci_user"
    MYSQL_PASSWORD: "ci_password"
    MYSQL_ROOT_PASSWORD: "ci_root_password"
  before_script:
    - apt-get update && apt-get -y install catch clang cmake libcurl4-gnutls-dev libmariadb-dev pkg-config
    - export CC=clang && export CXX=clang++
  script:
    - ./ci/cpplint.sh
    - mkdir ./build
    - cd ./build
    - cmake ../ -DJSON_BENCHMARK=ON
    - make -j4
    - ctest -V

package_debian10:
  image: debian:10
  stage: build
  before_script:
    - ./ci/gitlab-01-install-dependencies.sh
  script:
    - ./ci/gitlab-02-create-package.sh
  only:
    - tags
  artifacts:
    paths:
      - "weather-information-collector*.deb"
