# Use the official gcc image, based on debian.
# It can use version tags as well, like gcc:5.2.
# See https://hub.docker.com/_/gcc/ for more info.
image: gcc

build_gcc:
  stage: build
  before_script:
    - apt-get update && apt-get -y install catch cmake g++ libcurl4-gnutls-dev libjsoncpp-dev libmysql++-dev libboost-filesystem-dev
  script:
    - ./ci/cpplint.sh
    - mkdir ./build
    - cd ./build
    - cmake ../ -DJSON_BENCHMARK=ON
    - make -j4
    - ctest -V

# There is no official clang image at Docker Hub, so we just install clang into
# the GCC image. Oh, the irony...
build_clang:
  stage: build
  before_script:
    - apt-get update && apt-get -y install catch clang cmake libcurl4-gnutls-dev libjsoncpp-dev libmysql++-dev libboost-filesystem-dev
    - unlink /usr/bin/c++ && ln -s /usr/bin/clang++ /usr/bin/c++
    - unlink /usr/bin/cc && ln -s /usr/bin/clang /usr/bin/cc
    - export CC=clang && export CXX=clang++
  script:
    - ./ci/cpplint.sh
    - mkdir ./build
    - cd ./build
    - cmake ../ -DJSON_BENCHMARK=ON
    - make -j4
    - ctest -V

package_debian9:
  image: debian:9
  stage: build
  before_script:
    - ./ci/gitlab-01-install-dependencies.sh
  script:
    - ./ci/gitlab-02-create-package.sh
  only:
    - tags
  artifacts:
    paths:
      - "weather-information-collector*.deb"

package_ubuntu1804:
  image: ubuntu:bionic
  stage: build
  before_script:
    - ./ci/gitlab-01-install-dependencies.sh
  script:
    - ./ci/gitlab-02-create-package.sh
  only:
    - tags
  artifacts:
    paths:
      - "weather-information-collector*.deb"
