# Official gcc image at Docker Hub uses Debian 10 ("buster"), but buster does
# not contain libmysql++ anymore, so we use Debian 9 ("stretch") instead.
image: debian:9-slim

build_gcc:
  stage: build
  services:
  - mariadb:10.4
  variables:
    MYSQL_DATABASE: "weather_information_collector"
    MYSQL_USER: "ci_user"
    MYSQL_PASSWORD: "ci_password"
    MYSQL_ROOT_PASSWORD: "ci_root_password"
  before_script:
    - apt-get update && apt-get -y install catch cmake g++ libcurl4-gnutls-dev libjsoncpp-dev libmysql++-dev libboost-filesystem-dev pkg-config
    - export CC=gcc && export CXX=g++
  script:
    # ./ci/cpplint.sh # segfaults on g++ 6.3.0 in /usr/include/catch.hpp:9473:31
    - mkdir ./build
    - cd ./build
    - cmake ../ -DJSON_BENCHMARK=ON
    - make -j4
    - ctest -V

# There is no official clang image at Docker Hub.
build_clang:
  stage: build
  services:
  - mariadb:10.4
  variables:
    MYSQL_DATABASE: "weather_information_collector"
    MYSQL_USER: "ci_user"
    MYSQL_PASSWORD: "ci_password"
    MYSQL_ROOT_PASSWORD: "ci_root_password"
  before_script:
    - apt-get update && apt-get -y install catch clang cmake libcurl4-gnutls-dev libjsoncpp-dev libmysql++-dev libboost-filesystem-dev pkg-config
    - export CC=clang && export CXX=clang++
  script:
    - ./ci/cpplint.sh
    - mkdir ./build
    - cd ./build
    - cmake ../ -DJSON_BENCHMARK=ON
    - make -j4
    - ctest -V

package_debian9:
  image: debian:9
  stage: build
  before_script:
    - ./ci/gitlab-01-install-dependencies.sh
  script:
    - ./ci/gitlab-02-create-package.sh
  only:
    - tags
  artifacts:
    paths:
      - "weather-information-collector*.deb"

package_ubuntu1804:
  image: ubuntu:bionic
  stage: build
  before_script:
    - ./ci/gitlab-01-install-dependencies.sh
  script:
    - ./ci/gitlab-02-create-package.sh
  only:
    - tags
  artifacts:
    paths:
      - "weather-information-collector*.deb"
