language: cpp
compiler:
  - clang
  - gcc
sudo: false
dist: trusty
os:
  - linux
script:
  - ./ci/cpplint.sh
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j4
  - ctest -V
addons:
  apt:
    packages:
    - catch
    - g++
    - libcurl4-gnutls-dev
    - libjsoncpp-dev
notifications:
  email: false
