language: cpp
compiler:
  - clang
  - gcc
sudo: false
dist: bionic
os:
  - linux
services:
  - mysql
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS weather_information_collector"
  - mysql -e "GRANT ALL ON weather_information_collector.* TO 'travis'@'localhost';"
  - mysql -e "GRANT ALL ON weather_information_collector.* TO 'travis'@'%';"
  - mysql -e "GRANT ALL ON weather_information_collector.* TO 'travis'@'127.0.0.1';"
  - mysql -utravis --password="" -e "SHOW DATABASES;"
  - if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi
script:
  - ./ci/cpplint.sh
  - mkdir ./build
  - cd ./build
  - cmake ../ -DJSON_BENCHMARK=ON
  - make -j4
  - ctest -V
addons:
  apt:
    packages:
    - catch
    - g++-8
    - libcurl4-gnutls-dev
    - libjsoncpp-dev
    - libmariadb-dev
notifications:
  email: false
