# This version of the Dockerfile builds the *.deb package from the latest tagged
# version and then installs the package. That approach is slower and takes
# longer to build (and the image size is bigger, too), but it should be the most
# compatible approach.
#
# Image is based on Debian 9, because the current version of Debian 10 does not
# have the libmysql++ package yet.
FROM debian:9-slim
MAINTAINER Dirk Stolle <striezel-dev@web.de>

RUN mkdir -p /opt
WORKDIR /opt

# Update packages, install dependencies + root certificates.
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends catch cmake g++ git \
    libboost-filesystem-dev libcurl4-gnutls-dev libjsoncpp-dev libmysql++-dev \
    make pkg-config ca-certificates && \
    git clone https://gitlab.com/striezel/weather-information-collector.git
WORKDIR /opt/weather-information-collector
RUN ./ci/gitlab-01-install-dependencies.sh && \
    ./ci/gitlab-02-create-package.sh && \
    dpkg -i weather-information-collector*.deb && \
    ./ci/docker-cleanup.sh
# -- remove Git repository
WORKDIR /opt
RUN rm -rf /opt/weather-information-collector
# Create new user that will be used to run the program.
RUN useradd --create-home wic
USER wic
WORKDIR /home/wic
# Copy configuration files.
RUN mkdir .wic
COPY --chown=wic:wic configuration .wic
# Show version after build. (May differ from current SCM checkout.)
RUN weather-information-collector --version
# Run it!
CMD weather-information-collector
