# This version of the Dockerfile does not build the package itself, but it
# downloads a known Debian 10 package from GitLab instead. This speeds up the
# Docker image creation and has a smaller image size, but it may not always get
# the most up to date version.
FROM debian:10-slim
MAINTAINER Dirk Stolle <striezel-dev@web.de>

ENV DEB_DOWNLOAD_URL https://gitlab.com/striezel/weather-information-collector/-/jobs/1210422449/artifacts/download
RUN mkdir -p /opt
WORKDIR /opt
# Update packages, install dependencies + cleanup afterwards.
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y ca-certificates wget unzip && \
    wget -O download.zip "$DEB_DOWNLOAD_URL" && \
    unzip download.zip && rm -f download.zip && \
    apt-get install -y libc6 && \
    apt-get install -y libcurl3-gnutls libgcc1 libmariadb3 libstdc++6 && \
    dpkg -i weather-information-collector*.deb && \
    rm -f weather-information-collector*.deb && \
    apt-get purge -y wget unzip && apt-get clean
# Set timezone.
# Adjust the following line, if necessary.
# ENV TZ Etc/Utc
ENV TZ Europe/Berlin
RUN echo "$TZ" > /etc/timezone && \
    dpkg-reconfigure --frontend non-interactive tzdata && \
    echo "Current date is $(date)."
# Create new user that will be used to run the program.
RUN useradd --create-home wic
USER wic
WORKDIR /home/wic
# Copy configuration files.
RUN mkdir .wic
COPY --chown=wic:wic configuration .wic
# Show version after build. (May differ from current SCM checkout.)
RUN weather-information-collector --version
# Run it!
CMD weather-information-collector
