name: ARM 64

on: push

jobs:
  package:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends build-essential bzip2 ca-certificates cmake debhelper devscripts fakeroot g++ git lsb-release tar wget
          sudo apt-get -y install crossbuild-essential-arm64 dpkg-cross
      - name: Add ARM 64 package sources
        run: |
          sudo dpkg --add-architecture arm64
          sudo touch /etc/apt/sources.list.d/arm64.list
          echo "deb [arch=arm64] http://ports.ubuntu.com/ focal main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/arm64.list
          echo "deb [arch=arm64] http://ports.ubuntu.com/ focal-updates main restricted universe multiverse" | sudo tee --append /etc/apt/sources.list.d/arm64.list
          echo "deb [arch=arm64] http://ports.ubuntu.com/ focal-security main restricted universe multiverse" | sudo tee --append /etc/apt/sources.list.d/arm64.list
          sudo apt-get update || echo "Ignoring possible failures ..."
      - name: Install ARM 64 packages
        run: |
          sudo apt-get -y install --no-install-recommends catch:arm64 libcurl4-gnutls-dev:arm64 libmariadb-dev:arm64 pkg-config:arm64
      - name: Build package
        run: |
          TAG="${CI_COMMIT_TAG:-$(git describe | cut -d '-' -f 1)}"
          VERSION=$(echo $TAG | cut -c '2-')
          ARCH=$(dpkg --print-foreign-architectures)
          mkdir -p /opt/pkg && cd /opt/pkg
          wget -O weather-information-collector_${VERSION}.orig.tar.bz2 https https://gitlab.com/striezel/weather-information-collector/-/archive/${TAG}/weather-information-collector-${TAG}.tar.bz2
          tar -x --bzip2 -f weather-information-collector_${VERSION}.orig.tar.bz2
          mv weather-information-collector-${TAG} weather-information-collector-${VERSION}
          cd weather-information-collector-${VERSION}
          export CC=/usr/bin/aarch64-linux-gnu-gcc
          export CXX=/usr/bin/aarch64-linux-gnu-g++
          debuild -uc -us --host-arch arm64
      - name: Copy package to workspace
        run: |
          cd "$GITHUB_WORKSPACE"
          mkdir artifacts
          cp /opt/pkg/*.deb "$GITHUB_WORKSPACE"/artifacts/
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package-arm64-debian
          path: |
            artifacts/*
