name: GCC

on: push

jobs:
  ubuntu_20_04_gcc10:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake g++-10 git libcurl4-gnutls-dev libmariadb-dev pkg-config
      - name: Start MySQL database
        run: sudo systemctl start mysql.service
      - name: Show MySQL version information
        run: |
          mysql -uroot -proot -e "SHOW VARIABLES LIKE '%version%';"
      - name: Prepare MySQL database
        run: |
          mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS weather_information_collector"
          mysql -uroot -proot -e "GRANT ALL ON weather_information_collector.* TO 'root'@'localhost';"
          mysql -uroot --password=root -e "SHOW DATABASES;"
      - name: Adjust MySQL 8.0 authentication
        run: |
          mysql -uroot -proot -e "ALTER USER root@localhost IDENTIFIED WITH mysql_native_password BY ''; ALTER USER root@localhost IDENTIFIED BY 'root'; FLUSH PRIVILEGES;"
          mysql -uroot --password=root -e "SHOW DATABASES;"
      - name: Build
        run: |
          export CXX=g++-10
          export CC=gcc-10
          cd "$GITHUB_WORKSPACE"
          mkdir build
          cd build
          cmake ../ -DJSON_BENCHMARK=ON
          make -j4
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
  ubuntu_20_04_gcc9:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake g++-9 git libcurl4-gnutls-dev libmariadb-dev pkg-config
      - name: Start MySQL database
        run: sudo systemctl start mysql.service
      - name: Show MySQL version information
        run: |
          mysql -uroot -proot -e "SHOW VARIABLES LIKE '%version%';"
      - name: Prepare MySQL database
        run: |
          mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS weather_information_collector"
          mysql -uroot -proot -e "GRANT ALL ON weather_information_collector.* TO 'root'@'localhost';"
          mysql -uroot --password=root -e "SHOW DATABASES;"
      - name: Adjust MySQL 8.0 authentication
        run: |
          mysql -uroot -proot -e "ALTER USER root@localhost IDENTIFIED WITH mysql_native_password BY ''; ALTER USER root@localhost IDENTIFIED BY 'root'; FLUSH PRIVILEGES;"
          mysql -uroot --password=root -e "SHOW DATABASES;"
      - name: Build
        run: |
          export CXX=g++-9
          export CC=gcc-9
          cd "$GITHUB_WORKSPACE"
          mkdir build
          cd build
          cmake ../ -DJSON_BENCHMARK=ON
          make -j4
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
  ubuntu_18_04_gcc8:
    runs-on: ubuntu-18.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake g++-8 git libcurl4-gnutls-dev libmariadb-dev pkg-config
      - name: Start MySQL database
        run: sudo systemctl start mysql.service
      - name: Show MySQL version information
        run: |
          mysql -uroot -proot -e "SHOW VARIABLES LIKE '%version%';"
      - name: Prepare MySQL database
        run: |
          mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS weather_information_collector"
          mysql -uroot -proot -e "GRANT ALL ON weather_information_collector.* TO 'root'@'localhost';"
          mysql -uroot --password=root -e "SHOW DATABASES;"
      - name: Build
        run: |
          export CXX=g++-8
          export CC=gcc-8
          cd "$GITHUB_WORKSPACE"
          mkdir build
          cd build
          cmake ../ -DJSON_BENCHMARK=ON
          make -j4
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
